name: Auto-bump version on Merge
on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}
        uses: actions/checkout@v3
      - name: Bump version
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Git Setup
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - run: pip install bumpver
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}
        run: python -m bumpver update --patch -n
